spring:
  datasource:
    url: jdbc:h2:file:./server/data/project_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
server:
  servlet:
    session:
      timeout: 30m
